sudo: false
language: node_js
branches:
  only:
  - gh-pages
env:
  global:
    secure: VnTmmRVghoM1WcD6doqIvjRMBKw5RJ+IdOTeTqJpg8RDNdiLjZvHzyg084uL4K8IWs+7zf8XAjM+joU0EAcsEV6wl+QwkjJkV2jNy4BLQZ5A1+sfdBohIxSSdR8ceOLrgh71uTOqfsDpONNgB22OQiv+bLYcz//fFrRNs2jTGOQ=
